[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  framework = "#custom"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "contentful"]

[functions."scheduled-sitemap"]
  schedule = "@daily"